### PR TITLE
Update postman file to align with API Help docs, use path parameters, no hard-coded segments

### PR DESCRIPTION
**Pull request by dtk-DaveKarow**
Changed all /<placeholder_name_here>/ style URLs to use Postman's syntax for path params, where a colon is placed before placeholder (/:<placeholder_name_here>/

Swapped out some hard-coded segment names for :<segment_name> instead.

### CODE REVIEW

**Comment by dtk-DaveKarow** [comment]
Don't accept this one yet... I'd like to walk through the diff to validate all of my changes first.

**Review by dtk-DaveKarow — COMMENTED** [review]
Confirmed these all look as I intended them to in this pass:

1. All `<placeholder_name>` appearances in URL's now show as `:<placeholder_name>` which enhances the Postman experience, creating fields that the values can be easily pasted into without altering the URL itself.
2. The hard-coded `friendly_customers_2` segment name has been swapped out for a generic placeholder, `:<segment_name>`, in URLs.  It still remains in the raw JSON body examples in several commands. **[TODO: Look into making those JSON bodies parameterized the way path params are if possible]**
3. Only `{{base-url}}`, `{{workspace-id}}`, and `{{environment-id}}` are allowed to remain as variables that can be defined as scope of Global, Collection or Active Environment.  The following were converted from `{{}}` style variables to path param style variables with `:` preceding them: `:<apiKeyId>`, `:<traffictype-id>`, `:<traffic-type-id-or-name>`, 
4. Query param of `&tag` in was set to be disabled and `tag_test` was removed as a pre filled-in value in the GET Segments entry.

Open question: While `<>`'s wrapped around placeholders make them stand out better, such as `<feature_flag_name>`, they look a bit odd once preceded by path variable marker colon (`:`) such as this `:<feature_flag_name>` -- I would hate for someone unfamiliar with Postman to think the `:` is supposed to actually go in the path, and I'm wondering if the role of the `:` would be more clear if placeholders looked like this instead: `:feature_flag_name` --  I suppose that argument could go either way.

**Comment by dtk-DaveKarow** [comment]
@jebertz lets chat about this during the week.  Would love your input on the `:<placeholder_name>` vs `:placeholder_name` issue before I ask for an approval to merge.

**Comment by dtk-DaveKarow** [comment]
TODO's before approving and merging this PR:

- [ ] Replace hard-coded ws and env in “POST Open Change Request removing keys from a segment, with environment restricted approvers”
- [ ] Remove duplicated GET Segments entry

Longer term TODO's that could be more disruptive, and probably should wait:

- [ ] Update the generic ALL CAPS verbs (like GET) in Postman, with the Domain-specific, title-case verbs like (like List) in Docs.  Example: API docs say "List Segments" while Postman says "GET Segments" - both show "GET" as the operation.

**Comment by dtk-DaveKarow** [comment]
Longer term TODOs that I don't want to start until we review, merge and test this collection are below.
Just noting them here for visibility.
The idea is to review and test previously identified TODOs before starting the ones below, which involve moving stuff around and renaming things, to reduce complexity in review process.

- [ ] Align folder structure (including new alpha sort of folders) with API Documentation
- [ ] Align endpoint names with API Documentation (Example: API docs say "List Segments" while Postman says "GET Segments" - both show "GET" as the operation, so the current pattern of putting ALL CAPS operations in Postman is redundant)
- [ ] Identify any endpoints present in API docs that are missing from Postman (besides Create Traffic Types fixed in [97e6db7](https://github.com/splitio/public-api-postman/pull/29/commits/97e6db7cb3461bc26439076c5a12ab34cfe206b5))

**Review by jebertz — APPROVED** [review]
lgtm, thank you for doing this!

**Comment by jebertz** [comment]
> @jebertz lets chat about this during the week. Would love your input on the `:<placeholder_name>` vs `:placeholder_name` issue before I ask for an approval to merge.

I'm honestly pretty okay with either.  Have you seen other examples in the wild that tend one way or the other?

**Review by dtk-DaveKarow — COMMENTED** [review]
Missed one for GET Change Request

**Comment by dtk-DaveKarow** [comment]
@jebertz so now I've done the BIG change, by mimicking the folder structure and endpoint titles of the API docs at https://docs.split.io/v2-dev/reference/.  I also beautified JSON bodies for readability. The result is a massive diff.  Since my next goal is to have intern test all endpoints from here, I'm OK with not being able to reason about these via the diff.

**Review by jebertz — APPROVED** [review]
ship it!

**Pull request merged**
