### PR TITLE
Fix json format and make the file valid

### PR DESCRIPTION
**Pull request by harshal-moneylion**
When importing `prod.postman_environment.json`
postman throw this error fixing the file to work as expected 

image

Fixes: #32

### CODE REVIEW

**Comment by harshal-moneylion** [comment]
@dtk-DaveKarow can someone take a look?

**Comment by dtk-DaveKarow** [comment]
@harshal-moneylion will do.

**Comment by dtk-DaveKarow** [comment]
Looks good @harshal-moneylion.
@jebertz can can you approve and merge please?

**Review by dtk-DaveKarow — APPROVED** [review]
Looks good.

**Review by jebertz — APPROVED** [review]

**Pull request merged**
